#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

folder_to_watch="src/"

echo "Atualizando a versão"
npm version patch --no-git-tag-version

git add .

changes=$(git diff --cached --name-only --diff-filter=ACM $folder_to_watch)

echo $changes