#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

folder_to_watch="src/"

echo "Atualizando a versão"
npm version patch --no-git-tag-version

git add package.json package-lock.json

changes=$(git diff --cached --name-only --diff-filter=ACM)

echo $changes