#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

folder_to_watch="src/"
echo "Verificando se ocorreu mudanças nativas"

if [ ! -d "$folder_to_watch" ]; then
  echo "A pasta $folder_to_watch não existe!"
  exit 1
fi

changes=$(git diff --cached --name-only --diff-filter=ACM $folder_to_watch)


if [ -n "$changes" ]; then
  content=$(cat $1)
  echo "NATIVE: $content" > "$1"
  npm version patch --no-git-tag-version
fi

